class SystemGroups:
    ROLE_SYS_ADMIN = 'ROLE_SYS_ADMIN'
    ROLE_SYS_SERVICE = 'ROLE_SYS_SERVICE'
    ROLE_HOME_ADMIN = 'ROLE_HOME_ADMIN'
    ROLE_HOME_USER = 'ROLE_HOME_USER'

    values = [ROLE_SYS_ADMIN, ROLE_SYS_SERVICE, ROLE_HOME_ADMIN, ROLE_HOME_USER]
